import { Server as SocketServer, Socket } from 'socket.io';
import { prisma } from '../lib/prisma';

let ioInstance: SocketServer | null = null;

export function setupSocketHandlers(io: SocketServer): void {
  ioInstance = io;

  io.on('connection', (socket: Socket) => {
    console.log(`Socket connected: ${socket.id}`);

    socket.on('match:subscribe', ({ matchId }: { matchId: string }) => socket.join(`match:${matchId}`));
    socket.on('match:unsubscribe', ({ matchId }: { matchId: string }) => socket.leave(`match:${matchId}`));
    socket.on('ground:subscribe', ({ groundId }: { groundId: string }) => socket.join(`ground:${groundId}`));
    socket.on('take:subscribe', ({ takeId }: { takeId: string }) => socket.join(`take:${takeId}`));
    socket.on('user:subscribe', ({ userId }: { userId: string }) => socket.join(`user:${userId}`));
    socket.on('disconnect', () => console.log(`Socket disconnected: ${socket.id}`));
  });

  // Live score updates every 30 seconds
  setInterval(async () => {
    try {
      const liveMatches = await prisma.match.findMany({ where: { status: 'live' }, include: { sport: true } });
      for (const match of liveMatches) {
        let stats: Record<string, unknown> | null = null;
        try { stats = match.statsJson ? JSON.parse(match.statsJson) as Record<string, unknown> : null; } catch { continue; }
        if (!stats) continue;

        if (match.sportId === 'football' && typeof stats.minute === 'number') {
          const newMinute = Math.min(stats.minute + 1, 90);
          await prisma.match.update({
            where: { id: match.id },
            data: { statsJson: JSON.stringify({ ...stats, minute: newMinute }) },
          });
          io.to(`match:${match.id}`).emit('score:update', {
            matchId: match.id, homeScore: match.homeScore, awayScore: match.awayScore,
            minute: newMinute, sport: match.sportId,
          });
        }
      }
    } catch { /* non-fatal */ }
  }, 30000);

  // Match events + debate auto-generation every 2 minutes
  setInterval(async () => {
    try {
      const liveMatches = await prisma.match.findMany({ where: { status: 'live' } });
      if (!liveMatches.length || Math.random() > 0.1) return;

      const match = liveMatches[Math.floor(Math.random() * liveMatches.length)];
      const eventTypes: Record<string, string[]> = {
        football: ['goal', 'yellow_card', 'substitution', 'red_card'],
        tennis: ['ace', 'break_point', 'game_won'],
        cricket: ['wicket', 'boundary', 'six'],
        f1: ['overtake', 'pit_stop', 'fastest_lap'],
        badminton: ['smash', 'net_point', 'game_won'],
      };

      const sportEvents = eventTypes[match.sportId] || ['event'];
      const eventType = sportEvents[Math.floor(Math.random() * sportEvents.length)];

      io.to(`match:${match.id}`).emit('match:event', {
        matchId: match.id, type: eventType,
        data: { sport: match.sportId, time: new Date().toISOString() },
      });

      // Auto-generate debate for significant events
      const debateEvents = ['goal', 'red_card', 'wicket', 'overtake'];
      if (debateEvents.includes(eventType)) {
        const debate = await autoGenerateDebate(match, eventType);
        if (debate) {
          io.emit('debate:new', { debate, matchId: match.id });
        }
      }
    } catch { /* non-fatal */ }
  }, 120000);
}

async function autoGenerateDebate(match: { id: string; sportId: string; homeTeam: string; awayTeam: string }, trigger: string) {
  const templates: Record<string, { question: string; sideA: string; sideB: string }> = {
    goal: { question: `Was the goal the turning point of this match?`, sideA: 'Yes, changes everything', sideB: 'No, game is still open' },
    red_card: { question: `Was the red card the right call?`, sideA: 'Correct, clear foul', sideB: 'Terrible call, too harsh' },
    wicket: { question: `Is this the wicket that decides the match?`, sideA: 'Yes, match-winner', sideB: 'Too early to say' },
    overtake: { question: `Will ${match.homeTeam} hold position to the podium?`, sideA: 'Yes, they have the pace', sideB: 'No, tyre strategy will hurt' },
  };

  const template = templates[trigger];
  if (!template) return null;

  try {
    return await prisma.debate.create({
      data: {
        question: template.question,
        sideA: template.sideA,
        sideB: template.sideB,
        matchId: match.id,
        sportId: match.sportId,
        trigger,
        closedAt: new Date(Date.now() + 7 * 24 * 3600000),
      },
    });
  } catch { return null; }
}

export function emitToUser(userId: string, event: string, data: unknown): void {
  ioInstance?.to(`user:${userId}`).emit(event, data);
}
